# Generated by Django 4.1.7 on 2023-05-18 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='emailid',
        ),
    ]
